### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by undng** [Hackermen/termgram#9]
I am new at using Linux (and GitHub btw too), so probably do not understand something important, but i do not know what exactly. 
I am using Manjaro Linux. Command sudo pip3 install -r requirements.txt leads to next output:

``
```
`Requirement already satisfied: pyaes==1.6.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.6.1)
Collecting pyasn1==0.3.7
  Using cached pyasn1-0.3.7-py2.py3-none-any.whl (63 kB)
Collecting rsa==3.4.2
  Using cached rsa-3.4.2-py2.py3-none-any.whl (46 kB)
Collecting Telethon==0.15.5
  Using cached Telethon-0.15.5-py3-none-any.whl (236 kB)
Collecting urwid==1.3.1
  Using cached urwid-1.3.1.tar.gz (588 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 488, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 912, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 932, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 330, in invalid_unless_false
          raise DistutilsSetupError(f"{attr} is invalid.")
      distutils.errors.DistutilsSetupError: use_2to3 is invalid.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 85, in <module>
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-tze4tq4j/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 152, in setup
          raise SystemExit("error in {} setup command: {}".format(attrs['name'], msg))
      SystemExit: error in urwid setup command: use_2to3 is invalid.
      Couldn't build the extension module, trying without it...
      error in urwid setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
``

When i am trying to start up termgram, i get next error:

```
Traceback (most recent call last):
  File "/usr/local/bin/termgram", line 6, in <module>
    app.run()
  File "/home/andronik/termgram/termgram/app.py", line 34, in run
    init()
  File "/home/andronik/termgram/termgram/app.py", line 48, in init
    client = telethon.TelegramClient(config.SESSION_FILE, config.TELEGRAM_ID, config.TELEGRAM_HASH, update_workers=1)
TypeError: TelegramBaseClient.__init__() got an unexpected keyword argument 'update_workers'
```

**Comment by undng** [comment]
It turned out that pip installed wrong version of Telethon. I installed correct version, but now there is another error: When i try to login, it requires my telegram password, because i have enabled two-step verification. But i guess i can just turn it off, even though it would be nice to make it work with two-step verification.

**Comment by undng** [comment]
I changed login function in /termgram/termgram/app.py to look like this (not sure if it is correct)
```
def login():
    """First time login"""

    client.connect()
    while not client.is_user_authorized():
        phone = input("Enter phone: ")
        client.send_code_request(phone, force_sms=False)
        value = input("Enter login code: ")
        try:
            client.sign_in(phone, code=value)
        except telethon.errors.SessionPasswordNeededError:
            password = input("Enter password: ")
            client.sign_in(password=password)
   
            if not client.is_user_authorized(): 
                print("Failed to authenticate. Try again.\n")except KeyboardInterrupt:
            exit_program()

```

Termgram started to work with two-step verification. I guess its win
